const fs = require('fs');

const newWords = [
  { id: 25, kanji: "上", furigana: "うえ", romaji: "ue", english: "Up / Above", type: "noun", imageAlt: "A simple illustration of up or above", promptInstruction: "Identify the correct vocabulary:", sentence: "机の______にあります。", sentenceTarget: "上", sentenceMeaning: "It is on the desk.", distractors: ["下", "前", "後ろ"], sentenceDistractors: ["下", "前", "後ろ"] },
  { id: 26, kanji: "弟", furigana: "おとうと", romaji: "otouto", english: "Younger brother", type: "noun", imageAlt: "A simple illustration of a younger brother", promptInstruction: "Identify the correct vocabulary:", sentence: "私の______は学生です。", sentenceTarget: "弟", sentenceMeaning: "My younger brother is a student.", distractors: ["兄", "妹", "姉"], sentenceDistractors: ["兄", "妹", "姉"] },
  { id: 27, kanji: "言う", furigana: "いう", romaji: "iu", english: "Say / Tell", type: "verb", imageAlt: "A simple illustration of someone saying something", promptInstruction: "Identify the correct vocabulary:", sentence: "彼は「ありがとう」と______ました。", sentenceTarget: "言い", sentenceMeaning: "He said, 'Thank you'.", distractors: ["話し", "聞き", "書き"], sentenceDistractors: ["話し", "聞き", "書き"] },
  { id: 28, kanji: "子", furigana: "こ", romaji: "ko", english: "Child", type: "noun", imageAlt: "A simple illustration of a child", promptInstruction: "Identify the correct vocabulary:", sentence: "あの______は誰ですか。", sentenceTarget: "子", sentenceMeaning: "Who is that child?", distractors: ["人", "男", "女"], sentenceDistractors: ["人", "男", "女"] },
  { id: 29, kanji: "語", furigana: "ご", romaji: "go", english: "Language / Word", type: "noun", imageAlt: "A simple illustration of language", promptInstruction: "Identify the correct vocabulary:", sentence: "日本______を勉強します。", sentenceTarget: "語", sentenceMeaning: "I study Japanese.", distractors: ["話", "字", "本"], sentenceDistractors: ["話", "字", "本"] },
  { id: 30, kanji: "大", furigana: "だい", romaji: "dai", english: "Big / Large", type: "noun", imageAlt: "A simple illustration of something big", promptInstruction: "Identify the correct vocabulary:", sentence: "この木はとても______きいです。", sentenceTarget: "大", sentenceMeaning: "This tree is very big.", distractors: ["小", "高", "長"], sentenceDistractors: ["小", "高", "長"] },
  { id: 31, kanji: "押す", furigana: "おす", romaji: "osu", english: "Push / Press", type: "verb", imageAlt: "A simple illustration of pushing", promptInstruction: "Identify the correct vocabulary:", sentence: "ボタンを______てください。", sentenceTarget: "押し", sentenceMeaning: "Please press the button.", distractors: ["引き", "開け", "閉め"], sentenceDistractors: ["引き", "開け", "閉め"] },
  { id: 32, kanji: "教える", furigana: "おしえる", romaji: "oshieru", english: "Teach", type: "verb", imageAlt: "A simple illustration of teaching", promptInstruction: "Identify the correct vocabulary:", sentence: "先生が日本語を______ます。", sentenceTarget: "教え", sentenceMeaning: "The teacher teaches Japanese.", distractors: ["習い", "学び", "話し"], sentenceDistractors: ["習い", "学び", "話し"] },
  { id: 33, kanji: "英", furigana: "えい", romaji: "ei", english: "English / Splendid", type: "noun", imageAlt: "A simple illustration of English", promptInstruction: "Identify the correct vocabulary:", sentence: "私は______語を勉強しています。", sentenceTarget: "英", sentenceMeaning: "I am studying English.", distractors: ["国", "日", "中"], sentenceDistractors: ["国", "日", "中"] },
  { id: 34, kanji: "映る", furigana: "うつる", romaji: "utsuru", english: "Reflection / Projection", type: "verb", imageAlt: "A simple illustration of reflection", promptInstruction: "Identify the correct vocabulary:", sentence: "鏡に顔が______っています。", sentenceTarget: "映", sentenceMeaning: "My face is reflected in the mirror.", distractors: ["見え", "入り", "光り"], sentenceDistractors: ["見え", "入り", "光り"] },
  { id: 35, kanji: "後", furigana: "あと", romaji: "ato", english: "After / Later", type: "noun", imageAlt: "A simple illustration of later", promptInstruction: "Identify the correct vocabulary:", sentence: "______で電話します。", sentenceTarget: "後", sentenceMeaning: "I will call you later.", distractors: ["前", "今", "先"], sentenceDistractors: ["前", "今", "先"] },
  { id: 36, kanji: "姉", furigana: "あね", romaji: "ane", english: "Older sister", type: "noun", imageAlt: "A simple illustration of an older sister", promptInstruction: "Identify the correct vocabulary:", sentence: "私の______は学生です。", sentenceTarget: "姉", sentenceMeaning: "My older sister is a student.", distractors: ["妹", "兄", "弟"], sentenceDistractors: ["妹", "兄", "弟"] },
  { id: 37, kanji: "危ない", furigana: "あぶない", romaji: "abunai", english: "Dangerous", type: "adjective", imageAlt: "A simple illustration of danger", promptInstruction: "Identify the correct vocabulary:", sentence: "ここは______です。", sentenceTarget: "危ない", sentenceMeaning: "It is dangerous here.", distractors: ["安全", "痛い", "怖い"], sentenceDistractors: ["安全", "痛い", "怖い"] },
  { id: 38, kanji: "会う", furigana: "あう", romaji: "au", english: "Meet", type: "verb", imageAlt: "A simple illustration of meeting someone", promptInstruction: "Identify the correct vocabulary:", sentence: "明日、友達に______ます。", sentenceTarget: "会い", sentenceMeaning: "I will meet my friend tomorrow.", distractors: ["話し", "見", "行き"], sentenceDistractors: ["話し", "見", "行き"] },
  { id: 39, kanji: "秋", furigana: "あき", romaji: "aki", english: "Autumn / Fall", type: "noun", imageAlt: "A simple illustration of autumn", promptInstruction: "Identify the correct vocabulary:", sentence: "______は涼しいです。", sentenceTarget: "秋", sentenceMeaning: "Autumn is cool.", distractors: ["春", "夏", "冬"], sentenceDistractors: ["春", "夏", "冬"] },
  { id: 40, kanji: "甘い", furigana: "あまい", romaji: "amai", english: "Sweet", type: "adjective", imageAlt: "A simple illustration of sweet food", promptInstruction: "Identify the correct vocabulary:", sentence: "このケーキはとても______です。", sentenceTarget: "甘い", sentenceMeaning: "This cake is very sweet.", distractors: ["辛い", "苦い", "酸っぱい"], sentenceDistractors: ["辛い", "苦い", "酸っぱい"] },
  { id: 41, kanji: "開ける", furigana: "あける", romaji: "akeru", english: "Open", type: "verb", imageAlt: "A simple illustration of opening something", promptInstruction: "Identify the correct vocabulary:", sentence: "窓を______ましょう。", sentenceTarget: "開け", sentenceMeaning: "Let's open the window.", distractors: ["閉め", "見", "消し"], sentenceDistractors: ["閉め", "見", "消し"] },
  { id: 42, kanji: "朝御飯", furigana: "あさごはん", romaji: "asagohan", english: "Breakfast", type: "noun", imageAlt: "A simple illustration of breakfast", promptInstruction: "Identify the correct vocabulary:", sentence: "______を食べます。", sentenceTarget: "朝御飯", sentenceMeaning: "I eat breakfast.", distractors: ["昼御飯", "晩御飯", "お弁当"], sentenceDistractors: ["昼御飯", "晩御飯", "お弁当"] },
  { id: 43, kanji: "明日", furigana: "あした", romaji: "ashita", english: "Tomorrow", type: "noun", imageAlt: "A simple illustration of tomorrow", promptInstruction: "Identify the correct vocabulary:", sentence: "______は学校です。", sentenceTarget: "明日", sentenceMeaning: "Tomorrow is school.", distractors: ["今日", "昨日", "明後日"], sentenceDistractors: ["今日", "昨日", "明後日"] },
  { id: 44, kanji: "遊ぶ", furigana: "あそぶ", romaji: "asobu", english: "Play", type: "verb", imageAlt: "A simple illustration of playing", promptInstruction: "Identify the correct vocabulary:", sentence: "友達と______ます。", sentenceTarget: "遊び", sentenceMeaning: "I play with my friends.", distractors: ["学び", "働き", "休み"], sentenceDistractors: ["学び", "働き", "休み"] },
  { id: 45, kanji: "頭", furigana: "あたま", romaji: "atama", english: "Head", type: "noun", imageAlt: "A simple illustration of a head", promptInstruction: "Identify the correct vocabulary:", sentence: "______が痛いです。", sentenceTarget: "頭", sentenceMeaning: "My head hurts.", distractors: ["手", "足", "お腹"], sentenceDistractors: ["手", "足", "お腹"] },
  { id: 46, kanji: "新しい", furigana: "あたらしい", romaji: "atarashii", english: "New", type: "adjective", imageAlt: "A simple illustration of something new", promptInstruction: "Identify the correct vocabulary:", sentence: "______服を買いました。", sentenceTarget: "新しい", sentenceMeaning: "I bought new clothes.", distractors: ["古い", "高い", "安い"], sentenceDistractors: ["古い", "高い", "安い"] },
  { id: 47, kanji: "朝", furigana: "あさ", romaji: "asa", english: "Morning", type: "noun", imageAlt: "A simple illustration of morning", promptInstruction: "Identify the correct vocabulary:", sentence: "______、パンを食べます。", sentenceTarget: "朝", sentenceMeaning: "I eat bread in the morning.", distractors: ["昼", "夜", "夕方"], sentenceDistractors: ["昼", "夜", "夕方"] },
  { id: 48, kanji: "暖かい", furigana: "あたたかい", romaji: "atatakai", english: "Warm", type: "adjective", imageAlt: "A simple illustration of warmth", promptInstruction: "Identify the correct vocabulary:", sentence: "______コーヒーを飲みます。", sentenceTarget: "暖かい", sentenceMeaning: "I drink warm coffee.", distractors: ["冷たい", "熱い", "涼しい"], sentenceDistractors: ["冷たい", "熱い", "涼しい"] },
  { id: 49, kanji: "兄", furigana: "あに", romaji: "ani", english: "Older brother", type: "noun", imageAlt: "A simple illustration of an older brother", promptInstruction: "Identify the correct vocabulary:", sentence: "これは私の______です。", sentenceTarget: "兄", sentenceMeaning: "This is my older brother.", distractors: ["弟", "姉", "妹"], sentenceDistractors: ["弟", "姉", "妹"] },
  { id: 50, kanji: "足", furigana: "あし", romaji: "ashi", english: "Foot / Leg", type: "noun", imageAlt: "A simple illustration of a foot or leg", promptInstruction: "Identify the correct vocabulary:", sentence: "______が痛いです。", sentenceTarget: "足", sentenceMeaning: "My leg hurts.", distractors: ["手", "頭", "目"], sentenceDistractors: ["手", "頭", "目"] },
  { id: 51, kanji: "熱い", furigana: "あつい", romaji: "atsui", english: "Hot", type: "adjective", imageAlt: "A simple illustration of something hot", promptInstruction: "Identify the correct vocabulary:", sentence: "これは、______お茶です。", sentenceTarget: "熱い", sentenceMeaning: "This is hot tea.", distractors: ["冷たい", "暖かい", "涼しい"], sentenceDistractors: ["冷たい", "暖かい", "涼しい"] },
  { id: 52, kanji: "開く", furigana: "あく", romaji: "aku", english: "Open (intransitive)", type: "verb", imageAlt: "A simple illustration of a door opening", promptInstruction: "Identify the correct vocabulary:", sentence: "ドアが______ます。", sentenceTarget: "開き", sentenceMeaning: "The door opens.", distractors: ["閉まり", "動き", "止まり"], sentenceDistractors: ["閉まり", "動き", "止まり"] },
  { id: 53, kanji: "青", furigana: "あお", romaji: "ao", english: "Blue", type: "noun", imageAlt: "A simple illustration of the color blue", promptInstruction: "Identify the correct vocabulary:", sentence: "私は______が好きです。", sentenceTarget: "青", sentenceMeaning: "I like blue.", distractors: ["赤", "白", "黒"], sentenceDistractors: ["赤", "白", "黒"] },
  { id: 54, kanji: "赤", furigana: "あか", romaji: "aka", english: "Red", type: "noun", imageAlt: "A simple illustration of the color red", promptInstruction: "Identify the correct vocabulary:", sentence: "これは______いりんごです。", sentenceTarget: "赤", sentenceMeaning: "This is a red apple.", distractors: ["青", "白", "黄"], sentenceDistractors: ["青", "白", "黄"] },
  { id: 55, kanji: "飴", furigana: "あめ", romaji: "ame", english: "Candy / Sweets", type: "noun", imageAlt: "A simple illustration of candy", promptInstruction: "Identify the correct vocabulary:", sentence: "______を買いに行きます。", sentenceTarget: "飴", sentenceMeaning: "I am going to buy candy.", distractors: ["肉", "魚", "野菜"], sentenceDistractors: ["肉", "魚", "野菜"] },
  { id: 56, kanji: "厚い", furigana: "あつい", romaji: "atsui", english: "Thick", type: "adjective", imageAlt: "A simple illustration of something thick", promptInstruction: "Identify the correct vocabulary:", sentence: "______本です。", sentenceTarget: "厚い", sentenceMeaning: "It is a thick book.", distractors: ["薄い", "長い", "短い"], sentenceDistractors: ["薄い", "長い", "短い"] },
  { id: 57, kanji: "本", furigana: "ほん", romaji: "hon", english: "Book", type: "noun", imageAlt: "A simple illustration of a book", promptInstruction: "Identify the correct vocabulary:", sentence: "その______を読んでください。", sentenceTarget: "本", sentenceMeaning: "Please read that book.", distractors: ["紙", "手紙", "辞書"], sentenceDistractors: ["紙", "手紙", "辞書"] },
  { id: 58, kanji: "毎朝", furigana: "まいあさ", romaji: "maiasa", english: "Every morning", type: "noun", imageAlt: "A simple illustration of every morning", promptInstruction: "Identify the correct vocabulary:", sentence: "______、6時に起きます。", sentenceTarget: "毎朝", sentenceMeaning: "I wake up at 6 am every morning.", distractors: ["毎日", "毎晩", "毎週"], sentenceDistractors: ["毎日", "毎晩", "毎週"] },
  { id: 59, kanji: "短い", furigana: "みじかい", romaji: "mijikai", english: "Short", type: "adjective", imageAlt: "A simple illustration of something short", promptInstruction: "Identify the correct vocabulary:", sentence: "夏休みは______です。", sentenceTarget: "短い", sentenceMeaning: "Summer vacation is short.", distractors: ["長い", "高い", "低い"], sentenceDistractors: ["長い", "高い", "低い"] },
  { id: 60, kanji: "緑", furigana: "みどり", romaji: "midori", english: "Green", type: "noun", imageAlt: "A simple illustration of green", promptInstruction: "Identify the correct vocabulary:", sentence: "この木はとても______です。", sentenceTarget: "緑", sentenceMeaning: "This tree is very green.", distractors: ["青", "赤", "黄"], sentenceDistractors: ["青", "赤", "黄"] },
  { id: 61, kanji: "南", furigana: "みなみ", romaji: "minami", english: "South", type: "noun", imageAlt: "A simple illustration of south", promptInstruction: "Identify the correct vocabulary:", sentence: "京都は日本の______にあります。", sentenceTarget: "南", sentenceMeaning: "Kyoto is in the south of Japan.", distractors: ["北", "東", "西"], sentenceDistractors: ["北", "東", "西"] },
  { id: 62, kanji: "有名", furigana: "ゆうめい", romaji: "yumei", english: "Famous", type: "adjective", imageAlt: "A simple illustration of someone famous", promptInstruction: "Identify the correct vocabulary:", sentence: "これは______な絵です。", sentenceTarget: "有名", sentenceMeaning: "This is a famous picture.", distractors: ["元気", "静か", "きれい"], sentenceDistractors: ["元気", "静か", "きれい"] },
  { id: 63, kanji: "来月", furigana: "らいげつ", romaji: "raigetsu", english: "Next month", type: "noun", imageAlt: "A simple illustration of next month", promptInstruction: "Identify the correct vocabulary:", sentence: "______は私の誕生日です。", sentenceTarget: "来月", sentenceMeaning: "Next month is my birthday.", distractors: ["今月", "先月", "来年"], sentenceDistractors: ["今月", "先月", "来年"] },
  { id: 64, kanji: "悪い", furigana: "わるい", romaji: "warui", english: "Bad / Evil", type: "adjective", imageAlt: "A simple illustration of bad", promptInstruction: "Identify the correct vocabulary:", sentence: "昨日は気分が______かったです。", sentenceTarget: "悪", sentenceMeaning: "I felt bad yesterday.", distractors: ["良い", "高い", "安い"], sentenceDistractors: ["良い", "高い", "安い"] },
  { id: 65, kanji: "友達", furigana: "ともだち", romaji: "tomodachi", english: "Friend", type: "noun", imageAlt: "A simple illustration of friends", promptInstruction: "Identify the correct vocabulary:", sentence: "彼と私は良い______です。", sentenceTarget: "友達", sentenceMeaning: "He and I are good friends.", distractors: ["家族", "先生", "学生"], sentenceDistractors: ["家族", "先生", "学生"] },
  { id: 66, kanji: "留学生", furigana: "りゅうがくせい", romaji: "ryuugakusei", english: "International student", type: "noun", imageAlt: "A simple illustration of an international student", promptInstruction: "Identify the correct vocabulary:", sentence: "田中さんは私の______の友達です。", sentenceTarget: "留学生", sentenceMeaning: "Tanaka-san is my international student friend.", distractors: ["先生", "医者", "会社員"], sentenceDistractors: ["先生", "医者", "会社員"] },
  { id: 67, kanji: "鼻", furigana: "はな", romaji: "hana", english: "Nose", type: "noun", imageAlt: "A simple illustration of a nose", promptInstruction: "Identify the correct vocabulary:", sentence: "______をさわります。", sentenceTarget: "鼻", sentenceMeaning: "I touch my nose.", distractors: ["口", "目", "耳"], sentenceDistractors: ["口", "目", "耳"] },
  { id: 68, kanji: "若い", furigana: "わかい", romaji: "wakai", english: "Young", type: "adjective", imageAlt: "A simple illustration of young", promptInstruction: "Identify the correct vocabulary:", sentence: "彼女は______く見えます。", sentenceTarget: "若", sentenceMeaning: "She looks young.", distractors: ["古い", "新しい", "高い"], sentenceDistractors: ["古い", "新しい", "高い"] },
  { id: 69, kanji: "夕食", furigana: "ゆうしょく", romaji: "yuushoku", english: "Dinner", type: "noun", imageAlt: "A simple illustration of dinner", promptInstruction: "Identify the correct vocabulary:", sentence: "私はたいてい7時に______を食べます。", sentenceTarget: "夕食", sentenceMeaning: "I usually eat dinner at 7 PM.", distractors: ["朝食", "昼食", "夜食"], sentenceDistractors: ["朝食", "昼食", "夜食"] },
  { id: 70, kanji: "灰皿", furigana: "はいざら", romaji: "haizara", english: "Ashtray", type: "noun", imageAlt: "A simple illustration of an ashtray", promptInstruction: "Identify the correct vocabulary:", sentence: "机の上に______を置きます。", sentenceTarget: "灰皿", sentenceMeaning: "I'll put the ashtray on the table.", distractors: ["時計", "辞書", "財布"], sentenceDistractors: ["時計", "辞書", "財布"] },
  { id: 71, kanji: "時計", furigana: "とけい", romaji: "tokei", english: "Clock / Watch", type: "noun", imageAlt: "A simple illustration of a clock", promptInstruction: "Identify the correct vocabulary:", sentence: "その壁の______を見てください。", sentenceTarget: "時計", sentenceMeaning: "Please look at that wall clock.", distractors: ["鏡", "窓", "絵"], sentenceDistractors: ["鏡", "窓", "絵"] },
  { id: 72, kanji: "所", furigana: "ところ", romaji: "tokoro", english: "Place", type: "noun", imageAlt: "A simple illustration of a place", promptInstruction: "Identify the correct vocabulary:", sentence: "ここは私の行く______です。", sentenceTarget: "所", sentenceMeaning: "This is the place I am going.", distractors: ["時間", "人", "物"], sentenceDistractors: ["時間", "人", "物"] },
  { id: 73, kanji: "年", furigana: "とし", romaji: "toshi", english: "Year", type: "noun", imageAlt: "A simple illustration of a year", promptInstruction: "Identify the correct vocabulary:", sentence: "今年は2024______です。", sentenceTarget: "年", sentenceMeaning: "This year is 2024.", distractors: ["月", "日", "週"], sentenceDistractors: ["月", "日", "週"] },
  { id: 74, kanji: "隣", furigana: "となり", romaji: "tonari", english: "Neighbor / Next to", type: "noun", imageAlt: "A simple illustration of next to", promptInstruction: "Identify the correct vocabulary:", sentence: "私の______に座ってください。", sentenceTarget: "隣", sentenceMeaning: "Please sit next to me.", distractors: ["前", "後ろ", "向かい"], sentenceDistractors: ["前", "後ろ", "向かい"] }
];

let fileContent = fs.readFileSync('src/data.ts', 'utf8');

const injectionPoint = fileContent.indexOf('];\n\nexport const PRACTISE_QUESTIONS');
if (injectionPoint !== -1) {
  const wordsStr = newWords.map(w => '  ' + JSON.stringify(w)).join(',\n');
  const newContent = fileContent.slice(0, injectionPoint) + ',\n' + wordsStr + '\n' + fileContent.slice(injectionPoint);
  fs.writeFileSync('src/data.ts', newContent);
  console.log('Appended 50 new words.');
} else {
  console.log('Injection point not found.');
}
